### ISSUE TITLE
Does upgrading the vON module have potential to break anything?

### ISSUE THREAD

**Issue by Bucky21659** [vercas/vON#3]
By that I mean, if I upgrade the vON module I'm shipping in an addon from 1.1.1 to 1.3.4 does that have any potential to break files that have already been made and had data stored in them by vON?

**Comment by vercas** [comment]
Unfortunately, yes. And an incoming update (in a few months) will fully break compatibility.
Upgrading is highly recommended because newer releases contain bug fixes and performance improvements.  

I recommend you lock down the server for maintenance for a bit, get two version of vON side-by-side (your current one and the latest one), load every file with the old version and re-save them with the new one.  

This is the best solution I can think of for a specific server.  

If the addon is merely distributed to the public, then you could do something really clever:  
1. Distribute both versions.  
2. When loading a file, check if it was saved before a specific time. If it was, load with the old version, otherwise the new version.  
3. Always save with the new version.  

Ideally, when the addon is updated, it should pick that up somehow and store a timestamp.  
So, every file which was last modified before that is loaded with vON 1.1.1. The others would be saved with 1.3.4.  

This is more of a workaround; You may have to distribute multiple versions of vON forever.

**Comment by Bucky21659** [comment]
Ah, man!
It'd be nice if there was some sort of script that would do conversions though..
